// Type-safe i18n keys. Generated by hand for Story 1.3; Story 1.5 will
// extract a builder from src/i18n/fr.json (or replace this with a runtime
// keypath helper) once the i18n surface grows.

import type frJson from "@/i18n/fr.json";

type Leaves<T, P extends string = ""> = {
  [K in keyof T & string]: T[K] extends Record<string, unknown>
    ? Leaves<T[K], `${P}${P extends "" ? "" : "."}${K}`>
    : `${P}${P extends "" ? "" : "."}${K}`;
}[keyof T & string];

export type TranslationKey = Leaves<typeof frJson>;

export type TranslationFile = typeof frJson;
