// Type-safe i18n keys. Generated by hand for Story 1.3; Story 1.5 will
// extract a builder from src/i18n/fr.json (or replace this with a runtime
// keypath helper) once the i18n surface grows.

import type frJson from "@/i18n/fr.json";

// Exclude `_notes` — it's a JSON block reserved for translator comments,
// not a translatable leaf. Leaking it into TranslationKey lets callers
// resolve `t("_notes.xyz")` to whatever TODO string was parked there.
type ExcludedKey = "_notes";

type Leaves<T, P extends string = ""> = {
  [K in Exclude<keyof T, ExcludedKey> & string]: T[K] extends Record<string, unknown>
    ? Leaves<T[K], `${P}${P extends "" ? "" : "."}${K}`>
    : `${P}${P extends "" ? "" : "."}${K}`;
}[Exclude<keyof T, ExcludedKey> & string];

export type TranslationKey = Leaves<typeof frJson>;

export type TranslationFile = typeof frJson;
