// PLACEHOLDER — regenerated by `npm run db:types` (which runs
// `supabase gen types typescript --linked`) once the project is linked to a
// real Supabase project. Do not edit this file by hand; regen after every
// migration.
//
// Story 1.2 Phase 3 will overwrite this file with the real generated types.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
